### ISSUE TITLE
Rename the project to "voreutils"

### ISSUE THREAD

**Issue by jozsefsallai** [vlang/coreutils#18]
It makes sense, since this project is essentially replacing the C source with V, the name should also signify that. That way you'll also not get accused of copying the name. So, as a suggestion, I recommend replacing the letter C with V in the project's name too.

**Comment by JalonSolov** [comment]
Interesting idea, but not necessary.  `coreutils` has been rewritten in several other languages, and ported to other OSes, and the same name is used all the time.  Consider the full name to be `vlang/coreutils` if it helps.  A couple of examples of others:

https://github.com/uutils/coreutils
http://gnuwin32.sourceforge.net/packages/coreutils.htm
https://ports.macports.org/port/coreutils/summary
https://cygwin.com/packages/summary/coreutils.html
... etc., etc.

**Comment by darktohka** [comment]
I think this proposal makes complete sense. GNUWin32's and Mac's port, as well as the Cygwin port is still using Coreutils written in the C language. The Rust port of Coreutils still contains the letter R (coReutils), but since V is not present at all in this word it would be better representative of the project if it were renamed to Voreutils.

**Comment by spytheman** [comment]
> I think this proposal makes complete sense.

No, it does not, that is a troll attempt. 

Contributing the source of an util or two, will be a more productive use of your time, before proposing name changes.

**Comment by spytheman** [comment]
You can even contribute to a parallel repo, that you can name however you want.
This one will stay named `coreutils`.

**Comment by JalonSolov** [comment]
Contributing to a parallel repo would be sad... open source is supposed to be about collaboration, not exclusion.

However, if that is what someone decides to do, may they enjoy their efforts.
