### ISSUE TITLE
template?

### ISSUE THREAD

**Issue by tomByrer** [vlang/coreutils#4]
I've noticed there is no standard to the program structures.  V is easy to understand, but would be better if the codebase looked the same though out.  EG strange that even the version code is different between these 2 commands:
https://github.com/vlang/coreutils/blob/main/false/false.v#L7
https://github.com/vlang/coreutils/blob/main/whoami/whoami.v#L15

More standardized code would be easier to review, maintain, & automate (both in creation & testing).

**Comment by ShenTengTu** [comment]
PR #5 refers to the structure of `whoami.v` and implements a simple function of printing available parameters, which can be used as a reference.

**Comment by JalonSolov** [comment]
We are discussing things on discord about what we might need to add (including a template or a module, or whatever), whether we will start requiring a `_test.v` file with each command, etc.

One of the things under discussion is whether we do command line parsing like `whoami` or maybe use the `flag` module like `false`, `true`, and `yes`.  Possibly switch to the `cli` module for all.

**Comment by ShenTengTu** [comment]
I use `flag` module in `sleep`. It is simple and easy to use, but some frequently used options, such as `--help` and `--version`, need to be declared repeatedly in each CLI.

```v
// ...
help_opt := fp.bool('help', 0, false, 'display this help and exit')
version_opt := fp.bool('version', 0, false, 'output version information and exit')
args := fp.finalize() or {
error_exit(err.msg)
exit(1)
}
if help_opt {
println(fp.usage())
exit(0)
}
if version_opt {
println('$cmd_ns $fp.application_version')
exit(0)
}
// ...
```

**Comment by JalonSolov** [comment]
Yes, it would be nice if those were supported in the `flag` module instead.

**Comment by Flinner** [comment]
https://gist.github.com/Flinner/fa424110312de236e24d335d01f8dd97 this is the one i use

**Comment by JalonSolov** [comment]
`--help` and `--version` are now supported by default.  You _can_ still define them yourself, but I recommend removing them from your gist as they won't be needed often.

**Comment by JalonSolov** [comment]
The `common` module takes care of setting up command line, handling `--help` and `--version`, etc.
