### ISSUE TITLE
Small problem in wc output

### ISSUE THREAD

**Issue by JalonSolov** [vlang/coreutils#53]
Since we want these tools to be as compatible as possible with their GNU counterparts, issue like this need to be opened.  The reason is that many _other_ tools try to parse the output of the coreutils programs, and will fail if the differences are large.

I just attempted `cat README.md |bin/wc -l` and saw extra whitespace at the beginning of the line, and extra whitespace and a dash (`-`) after.  Here is the output from running first the V coreutils version, the the GNU version:
```
jamie@5950x coreutils]$ cat README.md |bin/wc -l
  144 -
[jamie@5950x coreutils]$ cat README.md |wc -l    
144
[jamie@5950x coreutils]$
```

Please make the outputs match, and test the output of the other options against GNU version of `wc`.

**Comment by JalonSolov** [comment]
@dundee ^^

**Comment by dundee** [comment]
I will fix it.
