### ISSUE TITLE
yes: low speed compared to the original

### ISSUE THREAD

**Issue by koplenov** [vlang/coreutils#70]
| [V](https://github.com/vlang/coreutils/blob/main/src/yes/yes.v) | [GNU](https://github.com/coreutils/coreutils/blob/master/src/yes.c) |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/25139987/132247093-36e51aef-db51-47de-8a99-018f8a8b890f.png) | ![image](https://user-images.githubusercontent.com/25139987/132247123-0a4ef4ff-51d0-4a07-9e9b-76078e3b22f6.png) |

[A Little Story About the `yes` Unix Command](https://endler.dev/2017/yes/)

**Comment by JalonSolov** [comment]
Nifty read - thanks for that.

For now, we are mainly concentrating on getting the tools done.  Optimizations have not really been considered.

When we do consider them, we will need to prioritize on which ones _need_ to be optimized, before we worry about optimizing just to be optimizing.

**Comment by JalonSolov** [comment]
On my system, I get 10.4 GiB/s from GNU `yes`, and latest V `yes` gives 10.1 GiB/s.  I'd say that's close enough.
